<?xml version="1.0" encoding="utf-8"?><Database Name="trabalho" Class="PessoaDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\mssqllocaldb;Initial Catalog=trabalho;Integrated Security=True" SettingsObjectName="WpfApplicationTeste.Properties.Settings" SettingsPropertyName="trabalhoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pessoas" Member="Pessoas">
    <Type Name="Pessoas">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefone" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DataNascimento" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>